## Example configuration file for dnscrypt-proxy

# server_names = ['scaleway-fr', 'google']

listen_addresses = ['0.0.0.0:53', '[::]:53']

max_clients = 250

ipv4_servers = true
ipv6_servers = false

dnscrypt_servers = true
doh_servers = true

require_nofilter_dnssec = false
require_dnssec = false
require_nolog = false
require_nofilter = false

fallback_resolvers = ['8.8.8.8:53', '4.2.2.4:53']

log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

block_ipv6 = false

cache = true
cache_size = 512
cache_min_ttl = 2400
cache_max_ttl = 86400